### ISSUE TITLE
groupId doesn't work

### ISSUE THREAD

**Issue by udleinati** [kestra-io/plugin-kafka#33]
### Expected Behavior

I'm expecting the consumer group be created after filling the property groupId with the topics that I have listed on property topic.

### Actual Behaviour

The property `groupId` indeed creates the consumer group but without any topic inside.

### Steps To Reproduce

Use this flow:

```
id: test
namespace: test
tasks:
  - id: log
    type: io.kestra.core.tasks.debugs.Echo
    format: The flow starts
  - id: consume
    type: io.kestra.plugin.kafka.Consume
    topic:
      - dev-my-topic
    groupId: 'kestra'
    properties:
      bootstrap.servers: 'my-kafka-server:9092'
      auto.offset.reset: earliest
    maxRecords: 100
```

When you remove the `groupId` from root level and add `group.id` inside `properties`, it does work but this the offset doesn't work as expected and just one partition will be read. The topic that I'm using for this test has 3 partitions.

### Environment Information

- Kestra Version: 0.11
- Plugin version: - the built in version -
- Operating System (OS / Docker / Kubernetes): Kestra helm release using the standalone version on Kubernetes
- Java Version (If not docker): Kestra helm release
