### ISSUE TITLE
Record headers should be deserialized as STRING and not as a string representation of the contents of a byte array.

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/plugin-kafka#65]
### Expected Behavior

Headers should be deserialized as STRING.

### Actual Behaviour

Currently, headers are returned as a string representation of the contents of a byte array. 

![kestra-consume-task-header](https://github.com/kestra-io/plugin-kafka/assets/1786576/0607a552-cf33-4c4f-a87d-1364c990ea73)

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

```yaml
id: kafka-consumer
namespace: dev
tasks:
  - id: consumer
    type: io.kestra.plugin.kafka.Consume
    topicPattern: kestra-.*
    properties:
      bootstrap.servers: localhost:9092
      group.id: kestra
      metadata.max.age.ms: 1000
    maxRecords: 10
    maxDuration: PT10S  
    keyDeserializer: STRING
    valueDeserializer: STRING   
```
