### ISSUE TITLE
Support Avro serdes other than Confluent

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/plugin-kafka#89]
### Feature description

Services such as AWS Glue Schema Registry (widely used for MSK) do not support Confluent. We should also support the Apache Avro serde for these cases

**Comment by anna-geller** [comment]
perhaps our Kafka experts @loicmathieu and @fhussonnois can help estimate the difficulty here - can you investigate how complex this would be? might be a quick win?

**Comment by loicmathieu** [comment]
Supporting any existing schema registry may be hard as it's a different serializer for each schema registry.

I know the Apicurio serializer support at least the Apicurio registry and the confluent registry so it may be a good start, but I have no idea if it supports AWS Glue. This needs investiguation.

**Comment by fhussonnois** [comment]
There is no easy solution for that and it will not be a quick-wink and the silver bullet doesn't exist. Also, we should not just think about Avro. Projects can use a Schema Registry with Avro, JSON, or Protobuf.

Right now: AVRO and JSON uses the Confluent Registry. But for example we cannot use plain JSON. For doing this, we have to first use a task to serialize data in JSON then use `STRING` as valueSerializer.

So, maybe should we add new props for declaring the vendor, e.g.:
```yaml
id: kafka_consume
namespace: company.team

tasks:
  - id: consume
    type: io.kestra.plugin.kafka.Consume
    topic: test_kestra
    properties:
      bootstrap.servers: localhost:9092
    serdeProperties:
      schema.registry.url: http://localhost:8085
    keyDeserializer: STRING
    valueDeserializer: AVRO
    valueDeserializerVendor: CONFLUENT      # Could be AWS_GLUE, NONE (for no registry)
```
